"use strict";
export const wage  = {
	data: [ 
	    {
	    	id:'1',
	    	wagesName:'铁盒-内芯包装0.05',
	    	procedure:{proName:'铁盒-内芯包装',billing:'计件工资',id:'p10'},
	    	wagesType:'ptdj',
	    	valuation:{
	    		valuationNumber:'1',
	    		valuationValue:'0.05'
	    	},
	    	comment:'1231231'
	    },
	    {
	    	id:'2',
	    	wagesName:'铁盒-粘双面胶0.000001',
	    	procedure:{proName:'铁盒-粘双面胶',billing:'计件工资',id:'p1'},
	    	wagesType:'qjdj',
	    	valuation:{
	    		valuationNumber:'1',
	    		valuationValue:'0.000001'
	    	}
	    },
	    {
	    	id:'3',
	    	wagesName:'组装-穿珠子0.12',
	    	procedure:{proName:'组装-穿珠子',billing:'计件工资',id:'p2'},
	    	wagesType:'普通定价',
	    	valuation:{
	    		valuationNumber:'1',
	    		valuationValue:'0.12'
	    	}
	    },
	    {
	    	id:'4',
	    	wagesName:'	包盒-打花0.06',
	    	procedure:{proName:'包盒-电镀盒组装',billing:'计件工资',id:'p3'},
	    	wagesType:'普通定价',
	    	valuation:{
	    		valuationNumber:'1',
	    		valuationValue:'0.06'
	    	}
	    },
	    {
	    	id:'5',
	    	wagesName:'包盒-包眼镜盒1',
	    	procedure:{proName:'包盒-包盒包底',billing:'计件工资',id:'p4'},
	    	wagesType:'普通定价',
	    	valuation:{
	    		valuationNumber:'1',
	    		valuationValue:'1'
	    	}
	    },
	    {
	    	id:'6',
	    	wagesName:'铁盒-内芯包装0.1120',
	    	procedure:{proName:'铁盒-内芯包装',billing:'计件工资',id:'p5'},
	    	wagesType:'普通定价',
	    	valuation:{
	    		valuationNumber:'1',
	    		valuationValue:'0.1120'
	    	}
	    },
	    {
	    	id:'7',
	    	wagesName:'铁盒-内芯包装0.1120',
	    	procedure:{proName:'铁盒-内芯包装',billing:'计件工资',id:'p6'},
	    	wagesType:'普通定价',
	    	valuation:{
	    		valuationNumber:'1',
	    		valuationValue:'0.1120'
	    	}
	    },
	    {
	    	id:'8',
	    	wagesName:'铁盒-内芯包装0.1120',
	    	procedure:{proName:'铁盒-内芯包装',billing:'计件工资',id:'p7'},
	    	wagesType:'普通定价',
	    	valuation:{
	    		valuationNumber:'1',
	    		valuationValue:'0.1120'
	    	}
	    },
	    {
	    	id:'9',
	    	wagesName:'铁盒-内芯包装0.1120',
	    	procedure:{proName:'铁盒-内芯包装',billing:'计件工资',id:'p8'},
	    	wagesType:'普通定价',
	    	valuation:{
	    		valuationNumber:'1',
	    		valuationValue:'0.1120'
	    	}
	    },
	    {
	    	id:'10',
	    	wagesName:'铁盒-内芯包装0.1120',
	    	procedure:{proName:'铁盒-内芯包装',billing:'计件工资',id:'p9'},
	    	wagesType:'普通定价',
	    	valuation:{
	    		valuationNumber:'1',
	    		valuationValue:'0.1120'
	    	}
	    },
    ]

}